### PR TITLE
Feature/pick single photo

### PR DESCRIPTION
**Pull request by ludoded**
On Collection Details scene there is a `plus` sign button on top bar. Once it's pressed you'll see the picker of photos

### CODE REVIEW

**Comment by bumi** [comment]
nice, will look at it asap.

**Comment by bumi** [comment]
How can we actually prevent the conflicts in the project.pbxproj? that files always changes. 
do we need it in git? :)

**Comment by ludoded** [comment]
You won’t be able to run the project without updated project.pbxproj
Do you want me to resolve the conflicts? Let me know which branches

**Comment by bumi** [comment]
yeah, but I was wondering as that file always changes and it looks pretty auto-generated. also it changes when I change my xcode settings. 

and yeah, we need to do fix the merge conflicts.

**Pull request merged**
